import { PageHero, SubPage } from "../components/Subpage";

const areas = [
  ["VinFast partnership", "Official VinFast service workshop partner and vehicle sales representative in the Philippines. DT Car supports customer consultation, vehicle delivery, technical service and after-sales care through a network of 12 service workshops."],
  ["Automotive services", "New and pre-owned vehicle sourcing, inspection, trading, maintenance, repair, rental and chauffeur arrangements, supported by an expanding customer and partner network."],
  ["Green GSM partnership", "Fleet repair and maintenance, vehicle supply and rental, driver recruitment, plus coordinated installation of advertising stickers, SIM dash cams, taxi meters and operational software for Green and premium LimoGreen vehicles."],
  ["V-Green infrastructure", "More than 100 potential charging sites sourced and assessed—including major fuel networks such as Rephil, SB Oil and FERC Cebu—with four charging stations completed."],
  ["Project implementation", "Local coordination, office decoration, field installation, quality control and multi-location rollout for corporate partners entering or expanding in the Philippine market."],
  ["DT Tour", "Flexible, full-package Philippines travel services with private transport and local support for individuals, families, groups and international clients."],
];

const leaders = [
  {src:"/images/profile-leader-john.jpg",name:"John Nguyen",role:"Chief Executive Officer",focus:"john",bio:"A visionary entrepreneur leading DT Car across automotive and multiple service industries, building a trusted, practical and innovative company in the Philippines."},
  {src:"/images/profile-leader-lisa.jpg",name:"Lisa Dong",role:"Director of Marketing & PR Department",focus:"lisa",bio:"Leads DT Car's marketing, public relations and brand communications, while coordinating partner-facing activities and professional project communications."},
  {src:"/images/profile-leader-tomy.jpg",name:"Tomy Pham",role:"Project Control Manager",focus:"tomy",bio:"Implements project plans, monitors progress, cost and quality, manages delivery risks and provides timely reporting so each scope meets the required standard."},
];

export default function AboutPage() {
  return <SubPage>
    <PageHero label="ABOUT DT CAR" title="Drive Trust." text="A Philippine-based multi-service company connecting automotive, green mobility, infrastructure, project execution and travel." image="/images/vinfast-signing-primary.jpeg" />
    <section className="aboutOverview"><div><p className="eyebrow">OUR COMPANY</p><h2>A trusted local execution partner.</h2></div><div><p>DT Car is a multi-service company operating across the automotive and service industries in the Philippines. We buy and sell new and pre-owned vehicles, provide vehicle rental and chauffeur arrangements, maintenance and repair, automotive support solutions, travel services and project contracting.</p><p>Beyond serving individual customers, DT Car works with major Vietnamese and international corporations in the Philippines. We combine local market knowledge, partner networks and disciplined project control to turn agreements into practical, accountable field operations.</p></div></section>
    <section className="aboutVision"><article><span>VISION</span><h3>A trusted growth partner</h3><p>To become a leading multi-service automotive and services company in the Philippines and a trusted partner for the Vietnamese community, local customers and international corporations.</p></article><article><span>MISSION</span><h3>Comprehensive solutions</h3><p>To deliver integrated automotive, mobility, travel and project services guided by Trust, Quality and Dedication.</p></article><figure><img src="/images/3DD3712B-4470-467B-9924-8B588C36DFBE.jpeg" alt="Lisa Dong at the VinFast and DT Car signing ceremony" /><figcaption>Lisa Dong at the VinFast and DT Car signing ceremony</figcaption></figure></section>
    <section className="aboutAreas"><p className="eyebrow">BUSINESS AREAS</p><h2>One local team. Six connected capabilities.</h2><div>{areas.map(([title,text],index) => <article key={title}><span>{String(index + 1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="aboutCommitment"><div><p className="eyebrow">SIGNED CONTRACTS & PARTNERSHIPS</p><h2>Agreements translated into field execution.</h2><p className="sectionLead">In 2025, DT Car signed business memoranda, service agreements and implementation contracts with Vingroup subsidiaries operating in the Philippine market.</p></div><div className="commitmentList"><article><strong>Official VinFast service partner</strong><p>Authorized technical service and after-sales support delivered through DT Car&apos;s 12-workshop network.</p></article><article><strong>Official VinFast sales representative</strong><p>Customer consultation, sales coordination and professional vehicle handover in the Philippines.</p></article><article><strong>Green GSM fleet partner</strong><p>Repair, maintenance, preparation and operational support for Green and LimoGreen fleets.</p></article><article><strong>Project implementation contracts</strong><p>Stickers, SIM dash cams, taxi meters, software, charging infrastructure and other coordinated field scopes.</p></article></div></section>
    <section className="aboutProof"><div className="aboutProofCopy"><p className="eyebrow">PROVEN EXECUTION</p><h2>From partnership to operation.</h2><p>DT Car combines local expertise, a strong partner network, disciplined project control and accountable delivery. Our teams support vehicle preparation, after-sales service, technology installation, charging infrastructure and multi-location rollouts.</p><ul><li>More than 10,000 GSM vehicles handled across all project scopes</li><li>Xentro Mall sticker, SIM dash-cam and taxi-meter implementation</li><li>V-Green site sourcing and charging-station construction</li><li>GSM driver recruitment, vehicle rental and vehicle supply</li><li>VinFast authorized service and vehicle sales support</li></ul></div><div className="aboutProofPhotos"><img src="/images/3C6CC438-ADE7-4E76-B073-117DB97C78A0.jpeg" alt="Green GSM fleet supported by DT Car" /><img src="/images/story-vgreen-site.jpeg" alt="DT Car V-Green charging infrastructure work" /></div></section>
    <section className="profileMetrics"><article><strong>12</strong><span>service workshops</span></article><article><strong>10,000+</strong><span>GSM vehicles handled</span></article><article><strong>100+</strong><span>charging sites sourced</span></article><article><strong>4</strong><span>charging stations completed</span></article></section>
    <section className="aboutAreas"><p className="eyebrow">COMPETITIVE ADVANTAGES</p><h2>Why partners choose DT Car.</h2><div><article><span>01</span><h3>Local expertise</h3><p>Practical understanding of Philippine customers, operations, locations and partner networks.</p></article><article><span>02</span><h3>Strong partner network</h3><p>Long-term cooperation with major Vietnamese and Philippine organizations.</p></article><article><span>03</span><h3>Proven execution</h3><p>Experienced teams able to organize multi-location and high-volume programs.</p></article><article><span>04</span><h3>Sustainability focus</h3><p>Mobility and infrastructure solutions designed to create durable value.</p></article><article><span>05</span><h3>Commitment to excellence</h3><p>Structured planning, progress monitoring, cost control and accountable delivery.</p></article><article><span>06</span><h3>Integrated services</h3><p>Automotive, fleet, infrastructure, project and travel capabilities coordinated through one company.</p></article></div></section>
    <section className="aboutCommitment"><div><p className="eyebrow">OUR COMMITMENTS</p><h2>Clear, customized and accountable.</h2></div><div className="commitmentList"><article><strong>Competitive, transparent pricing</strong><p>A clear cost structure with no hidden fees, supporting fairness and value for every client.</p></article><article><strong>Detailed implementation planning</strong><p>Customized strategies aligned with each client&apos;s needs and market requirements.</p></article><article><strong>End-to-end project management</strong><p>Full process control from planning to completion, focused on compliance, efficiency and timely delivery.</p></article><article><strong>Client-focused approach</strong><p>Practical, sustainable services designed to maximize long-term customer and partner benefits.</p></article></div></section>
    <section className="profileGrowth"><div><p className="eyebrow">PARTNERSHIP FOR GROWTH</p><h2>Green. Sustainable. Efficient.</h2><p>With credibility, experience and sustainable partnerships, DT Car is ready to accompany organizations expanding and developing in the Philippines. We aim to build long-term value through reliable execution and a greener, more efficient mobility ecosystem.</p></div><div className="growthPhotos"><img src="/images/vinfast-signing-primary.jpeg" alt="DT Car and VinFast signing ceremony" /><img src="/images/3DD3712B-4470-467B-9924-8B588C36DFBE.jpeg" alt="Lisa Dong signing the VinFast partnership agreement" /></div></section>
    <section className="leadership aboutLeadership"><p className="eyebrow">MEET OUR BEST TEAM</p><h2>DT Car leadership.</h2><div className="leaderGrid">{leaders.map(({src,name,role,focus,bio}) => <article key={name}><div className={`leaderPortrait ${focus}`}><img src={src} alt={`${name}, ${role}`} /></div><h3>{name}</h3><p className="leaderRole">{role}</p><p className="leaderBio">{bio}</p></article>)}</div></section>
    <section className="aboutContact"><p className="eyebrow">CONTACT US</p><h2>Let&apos;s build the next project together.</h2><p>Please contact us during business hours for the fastest support. We respond to email within 24 working hours, and all customer information is treated as strictly confidential.</p><div><a href="tel:+639498768888">+63 949 876 8888</a><a href="tel:+639060185666">+63 906 018 5666</a><a href="mailto:management@dtcar.ph">management@dtcar.ph</a><a href="https://www.facebook.com/profile.php?id=61550266324189" target="_blank" rel="noreferrer">Message DT Car in English</a></div><p className="contactAddress">Makati, Metro Manila, Philippines · https://dtcar.ph</p></section>
  </SubPage>;
}
