"use client";

import { useState } from "react";

const projects = [
  { tag: "VINFAST", title: "Sales & aftersales ecosystem", text: "Vehicle sales support and a growing network of 12 service workshops across the Philippines.", image: "/images/vinfast-signing-primary.jpeg" },
  { tag: "GREEN GSM", title: "10,000+ vehicles delivered", text: "Software, dash cams, taxi meters, stickers, driver recruitment, vehicle rental and fleet sales — including Green and LimoGreen.", image: "/images/gsm-fleet.jpeg" },
  { tag: "V-GREEN", title: "Charging network expansion", text: "100+ sites sourced and evaluated, with four charging stations completed and more in development.", image: "/images/vgreen-site.jpeg" },
  { tag: "XENTROMALL", title: "Mobility technology rollout", text: "Sticker installation, SIM-enabled dash cams and taxi meter deployment for operational fleets.", image: "/images/xentromall.jpeg" },
];

const stories = [
  { date: "WORKSHOP", title: "Building dependable after-sales support through 12 service workshops", image: "/images/235993FA-122C-4900-BD39-EAC455381A5A.jpeg", href: "/news/vinfast-authorized-workshop-network" },
  { date: "SPECIAL DELIVERY", title: "VinFast handover for Miss Universe Philippines 2025 Emmanuelle Tiglao", image: "/images/0437D0EE-D496-4E39-AE62-FBBED4F4CC96.jpeg", href: "/news/vinfast-delivery-emmanuelle-tiglao" },
  { date: "GSM PROJECT", title: "Inside a 10,000+ vehicle technology rollout", image: "/images/3C6CC438-ADE7-4E76-B073-117DB97C78A0.jpeg", href: "/news/gsm-10000-vehicle-technology-rollout" },
  { date: "VINFAST OWNERS EVENT", title: "DT Car supports a community event for VinFast car owners", image: "/images/ADA2D56D-6A8A-41EE-AEE3-B741805613BB.jpeg", href: "/news/vinfast-car-owners-event" },
];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [contactOpen, setContactOpen] = useState(false);
  return (
    <main>
      <div className="topbar"><span>Makati, Metro Manila, Philippines</span><div><a href="mailto:management@dtcar.ph">management@dtcar.ph</a><span className="sep">•</span><a href="tel:+639060185666">+63 906 018 5666</a></div></div>
      <header className="header">
        <a className="brand logoBrand" href="#top" aria-label="DT Car home"><img src="/images/dtcar-logo.png" alt="DT Car"/></a>
        <button className="menuButton" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? "×" : "☰"}</button>
        <nav className={menuOpen ? "nav open" : "nav"}><a href="/">Home</a><a href="/about">About</a><a href="/business">Business</a><a href="/projects">Projects</a><a href="/news">News</a><a href="/travel">Travel</a><div className="langLinks"><a href="/">EN</a><a href="/vi">VI</a><a href="/zh">中文</a></div><button className="navCta" onClick={() => setContactOpen(true)}>Message us</button></nav>
      </header>
      <section className="hero" id="top"><div className="heroImage"/><div className="heroShade"/><div className="heroContent"><p className="eyebrow light">DT CAR PHILIPPINES</p><h1>Drive Trust.<br/>Deliver with confidence.</h1><p className="heroLead">An integrated automotive, mobility and project execution company connecting trusted partners with the Philippine market.</p><div className="heroActions"><a className="primary" href="#business">Explore our business</a><button className="textButton" onClick={() => setContactOpen(true)}>Talk to our team <span>↗</span></button></div></div><div className="heroNote">Automotive · Mobility · Infrastructure · Travel</div></section>
      <section className="intro section" id="about"><div><p className="eyebrow">WHO WE ARE</p><h2>A local team with the scale to execute.</h2></div><div><p>DT Car helps automotive and mobility brands move from strategy to real-world operations — from vehicle sales and aftersales to nationwide fleet deployment and charging infrastructure.</p><a className="inlineLink" href="/about">Discover our story <span>→</span></a></div></section>
      <section className="stats"><div><strong>12</strong><span>Service workshops</span></div><div><strong>10,000+</strong><span>GSM vehicles delivered</span></div><div><strong>100+</strong><span>V-Green sites sourced</span></div><div><strong>4</strong><span>Charging stations built</span></div></section>
      <section className="section business" id="business"><div className="sectionHead"><div><p className="eyebrow">WHAT WE DO</p><h2>One company. Multiple capabilities.</h2></div><p>Built around the needs of partners and customers in the Philippines.</p></div><div className="businessGrid">
        <article className="businessCard large used"><div className="cardShade"/><div className="cardContent"><span>01</span><h3>Automotive</h3><p>VinFast vehicles, used-car sourcing, inspection, buying and selling — connected to our specialist social channels.</p><button onClick={() => setContactOpen(true)}>Visit sales channels →</button></div></article>
        <article className="businessCard project"><div className="cardShade"/><div className="cardContent"><span>02</span><h3>Project Execution</h3><p>Fleet technology rollout, installation and field operations at scale.</p><a href="/projects">View projects →</a></div></article>
        <article className="businessCard fleet"><div className="cardShade"/><div className="cardContent"><span>03</span><h3>Fleet Solutions</h3><p>Vehicle supply, rental, driver recruitment and operational support.</p><a href="/business">Our capabilities →</a></div></article>
        <article className="businessCard travel" id="travel"><div className="cardShade"/><div className="cardContent"><span>04</span><h3>Philippines Travel</h3><p>Curated tours and local experiences for Vietnamese, Chinese and international travelers.</p><a href="/travel">Visit travel page →</a></div></article>
      </div></section>
      <section className="projects section" id="projects"><div className="sectionHead"><div><p className="eyebrow">SELECTED PROJECTS</p><h2>Partnerships that move markets.</h2></div><p>From agreements to deployment, our teams turn plans into measurable operations.</p></div><div className="projectGrid">{projects.map((item) => <article key={item.tag} className="projectCard"><div className="projectImage" style={{backgroundImage:`url('${item.image}')`}}/><div className="projectBody"><span>{item.tag}</span><h3>{item.title}</h3><p>{item.text}</p><a href={`/projects#${item.tag.toLowerCase().replace(" ", "-")}`}>Learn more →</a></div></article>)}</div></section>
      <section className="process"><div className="processImage"/><div className="processBody"><p className="eyebrow light">HOW WE WORK</p><h2>From opportunity<br/>to operation.</h2><ol><li><span>01</span><div><strong>Understand</strong><p>Local insight, partner objectives and market realities.</p></div></li><li><span>02</span><div><strong>Build</strong><p>Teams, sites, systems and detailed deployment plans.</p></div></li><li><span>03</span><div><strong>Deliver</strong><p>Hands-on execution with accountable field operations.</p></div></li></ol></div></section>
      <section className="section news" id="news"><div className="sectionHead"><div><p className="eyebrow">LATEST STORIES</p><h2>News from the field.</h2></div><a className="inlineLink" href="/news">View all news <span>→</span></a></div><div className="storyGrid">{stories.map((item) => <article key={item.title}><div className="storyImage" style={{backgroundImage:`url('${item.image}')`}}/><span>{item.date}</span><h3>{item.title}</h3><a href={item.href}>Read story →</a></article>)}</div></section>
      <section className="cta" id="contact"><p className="eyebrow light">START A CONVERSATION</p><h2>Let&apos;s build what&apos;s next.</h2><p>Choose English, Vietnamese or Chinese and our team will connect you with the right channel.</p><button className="primary" onClick={() => setContactOpen(true)}>Message DT Car</button></section>
      <footer><div className="footerBrand"><a className="footerLogo" href="#top" aria-label="DT Car home"><img src="/images/dtcar-logo.png" alt="DT Car"/></a><p>Drive Trust.</p></div><div><strong>Company</strong><a href="/">Home</a><a href="/about">About us</a><a href="/business">Business</a><a href="/projects">Projects</a><a href="/news">News</a></div><div><strong>Connect</strong><button onClick={() => setContactOpen(true)}>Facebook Pages</button><a target="_blank" rel="noreferrer" href="https://www.tiktok.com/@vinfastdtcar">TikTok</a><a href="mailto:management@dtcar.ph">Email us</a></div><div><strong>Contact</strong><a href="tel:+639498768888">+63 949 876 8888</a><a href="tel:+639060185666">+63 906 018 5666</a><span>Makati, Metro Manila</span></div><small>© 2026 DT Car Philippines. All rights reserved.</small></footer>
      {contactOpen && <div className="modalBack" onClick={() => setContactOpen(false)}><div className="modal" onClick={(e) => e.stopPropagation()}><button className="close" onClick={() => setContactOpen(false)}>×</button><p className="eyebrow">MESSAGE DT CAR</p><h2>Choose your channel</h2><p>Open the DT Car Page that matches your preferred language or service.</p><div className="channelList"><a target="_blank" rel="noreferrer" href="https://m.me/61550266324189"><b>English / Filipino</b><span>Facebook Messenger →</span></a><a target="_blank" rel="noreferrer" href="https://m.me/dtcarphil"><b>Tiếng Việt</b><span>Facebook Messenger →</span></a><a target="_blank" rel="noreferrer" href="https://m.me/61581792126050"><b>한국어</b><span>Facebook Messenger →</span></a><a target="_blank" rel="noreferrer" href="https://m.me/61552426496371"><b>中文</b><span>Facebook Messenger →</span></a><a target="_blank" rel="noreferrer" href="https://www.facebook.com/dulichphilippinesdttour"><b>Philippines Travel</b><span>DT Tour Facebook →</span></a><a target="_blank" rel="noreferrer" href="https://www.tiktok.com/@vinfastdtcar"><b>Vehicle videos</b><span>TikTok @vinfastdtcar →</span></a></div><a className="phoneLink" href="tel:+639060185666">Or call +63 906 018 5666</a></div></div>}
    </main>
  );
}
