import { PageHero, SubPage } from "../components/Subpage";
const fields=[["Hợp tác VinFast","Đại diện bán xe, tư vấn giao xe, dịch vụ kỹ thuật và hậu mãi qua mạng lưới 12 xưởng dịch vụ."],["Dịch vụ ô tô","Mua bán xe mới và xe đã qua sử dụng, kiểm tra, bảo dưỡng, sửa chữa, thuê xe và tài xế."],["Green GSM","Hỗ trợ hơn 10.000 xe Green GSM và LimoGreen: phần mềm, SIM dash cam, taxi meter, sticker, tuyển tài xế, thuê và bán xe."],["Hạ tầng V-Green","Tìm kiếm và đánh giá hơn 100 địa điểm, gồm nhiều chuỗi cây xăng; đã hoàn thành 4 trạm sạc."],["Triển khai dự án","Điều phối địa phương, lắp đặt hiện trường, trang trí văn phòng, kiểm soát chất lượng và triển khai đa điểm."],["DT Tour","Tour Philippines linh hoạt, xe riêng và hỗ trợ tại địa phương cho cá nhân, gia đình và đoàn khách."]];
const leaders=[["/images/profile-leader-john.jpg","John Nguyen","Giám đốc điều hành"],["/images/profile-leader-lisa.jpg","Lisa Dong","Giám đốc Phòng Marketing & PR"],["/images/profile-leader-tomy.jpg","Tomy Pham","Quản lý kiểm soát dự án"]];
export default function VietnamesePage(){return <SubPage>
<PageHero label="DT CAR PHILIPPINES" title="Drive Trust." text="Đối tác triển khai tại Philippines trong các lĩnh vực ô tô, giao thông xanh, hạ tầng, dự án và du lịch." image="/images/6677E51B-6A07-41EA-A0D6-81F5692DE7A6.jpeg"/>
<section className="aboutOverview"><div><p className="eyebrow">VỀ CHÚNG TÔI</p><h2>Đối tác triển khai đáng tin cậy.</h2></div><div><p>DT Car là công ty đa dịch vụ hoạt động trong ngành ô tô và dịch vụ tại Philippines. Chúng tôi mua bán xe mới và xe đã qua sử dụng, cho thuê xe và tài xế, bảo dưỡng–sửa chữa, triển khai dự án và cung cấp dịch vụ du lịch.</p><p>DT Car hợp tác cùng nhiều doanh nghiệp Việt Nam và quốc tế, kết hợp hiểu biết thị trường địa phương, mạng lưới đối tác và quản trị dự án để biến thỏa thuận thành kết quả thực tế.</p></div></section>
<section className="aboutVision"><article><span>TẦM NHÌN</span><h3>Đối tác tăng trưởng đáng tin cậy</h3><p>Trở thành công ty ô tô và dịch vụ đa ngành hàng đầu tại Philippines.</p></article><article><span>SỨ MỆNH</span><h3>Giải pháp toàn diện</h3><p>Cung cấp giải pháp tích hợp dựa trên Uy tín, Chất lượng và Tận tâm.</p></article><figure><img src="/images/3DD3712B-4470-467B-9924-8B588C36DFBE.jpeg" alt="Lisa Dong tại lễ ký kết VinFast"/><figcaption>Lisa Dong tại lễ ký kết hợp tác VinFast</figcaption></figure></section>
<section className="profileMetrics"><article><strong>12</strong><span>xưởng dịch vụ</span></article><article><strong>10.000+</strong><span>xe GSM đã triển khai</span></article><article><strong>100+</strong><span>địa điểm trạm sạc</span></article><article><strong>4</strong><span>trạm sạc đã xây dựng</span></article></section>
<section className="aboutAreas"><p className="eyebrow">LĨNH VỰC HOẠT ĐỘNG</p><h2>Một đội ngũ, sáu năng lực kết nối.</h2><div>{fields.map(([t,d],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="profileGrowth"><div><p className="eyebrow">HỢP ĐỒNG & ĐỐI TÁC</p><h2>Từ ký kết đến triển khai.</h2><p>DT Car đã ký và triển khai các thỏa thuận với VinFast, Green GSM, V-Green và các đối tác tại Philippines.</p></div><div className="growthPhotos"><img src="/images/vinfast-signing-primary.jpeg" alt="Lễ ký kết DT Car và VinFast"/><img src="/images/3C6CC438-ADE7-4E76-B073-117DB97C78A0.jpeg" alt="Đội xe Green GSM"/></div></section>
<section className="aboutCommitment"><div><p className="eyebrow">CAM KẾT</p><h2>Minh bạch, phù hợp và có trách nhiệm.</h2></div><div className="commitmentList"><article><strong>Chi phí rõ ràng</strong><p>Mức giá cạnh tranh, minh bạch và không có chi phí ẩn.</p></article><article><strong>Kế hoạch chi tiết</strong><p>Giải pháp theo nhu cầu khách hàng và thị trường.</p></article><article><strong>Quản lý toàn trình</strong><p>Kiểm soát tiến độ, chất lượng và chi phí đến nghiệm thu.</p></article><article><strong>Lấy khách hàng làm trung tâm</strong><p>Tạo giá trị thiết thực và bền vững.</p></article></div></section>
<section className="leadership aboutLeadership"><p className="eyebrow">BAN LÃNH ĐẠO</p><h2>Đội ngũ DT Car.</h2><div className="leaderGrid">{leaders.map(([src,n,r])=><article key={n}><div className="leaderPortrait"><img src={src} alt={n}/></div><h3>{n}</h3><p className="leaderRole">{r}</p></article>)}</div></section>
<section className="aboutContact"><p className="eyebrow">LIÊN HỆ</p><h2>Trao đổi cùng DT Car.</h2><p>Kênh tiếng Việt dành cho khách hàng muốn được tư vấn bằng tiếng Việt.</p><div><a href="tel:+639498768888">+63 949 876 8888</a><a href="tel:+639060185666">+63 906 018 5666</a><a href="mailto:management@dtcar.ph">management@dtcar.ph</a><a href="https://www.facebook.com/dtcarphil" target="_blank" rel="noreferrer">Nhắn tin bằng tiếng Việt</a></div></section>
</SubPage>}
