import { PageHero, SubPage } from "../components/Subpage";

const photos=["3B201622-AA7A-4A05-B30C-C22C209A3814.jpeg","91526570-951A-4990-A2C8-BCAE9773E638.jpeg","5DADBE0B-BEDD-4ED2-8838-1DBAF10535DA.jpeg","263FB8F1-0B32-4CF2-A681-EB6CCCD9D434.jpeg","4B014B84-54B4-4E2C-B984-AF8DB0B1BBCF.jpeg","BEBB1179-9D48-4222-B07C-FAAD69DE40F0.jpeg","A4857DB4-1CEC-48EB-85F1-563DD51DB9A0.jpeg","FB2022D8-E30A-4A48-A324-52203B363079.jpeg","360EFD10-780F-41E9-8A38-905566633118.jpeg","85F9AFEC-BC83-4902-8DDD-83A832C18996.jpeg"].map(name=>`/images/${name}`);

export default function TravelPage(){return <SubPage>
  <PageHero label="DT TOUR · PHILIPPINES" title="Explore more of the Philippines." text="Private, flexible journeys designed with local knowledge—from heritage towns and mountain escapes to islands, waterfalls and yacht experiences." image="/images/BEBB1179-9D48-4222-B07C-FAAD69DE40F0.jpeg"/>
  <section className="detailIntro"><p className="eyebrow">TRAVEL WITH DT TOUR</p><div><h2>Real places. Thoughtful itineraries. Local support.</h2><p>DT Tour plans complete Philippines experiences for Vietnamese, Chinese and international guests. Our team coordinates itineraries, private transport, local assistance and activity reservations around the way each guest wants to travel.</p><a className="primary darkPrimary" target="_blank" rel="noreferrer" href="https://m.me/dulichphilippinesdttour">Plan a trip on Messenger</a></div></section>
  <section className="detailGrid"><article><span>01</span><h3>Heritage &amp; culture</h3><p>Historic architecture, local food and flexible private-day itineraries.</p></article><article><span>02</span><h3>Nature &amp; highlands</h3><p>Waterfalls, forest pools, hot springs and cool-weather retreats.</p></article><article><span>03</span><h3>Islands &amp; the sea</h3><p>Yachts, beaches, water activities and coastal escapes planned end to end.</p></article></section>
  <section className="tourGallery"><div><p className="eyebrow">REAL DT TOUR JOURNEYS</p><h2>Photographs from the places we take our guests.</h2></div><div className="tourMasonry">{photos.map((src,i)=><figure key={src}><img src={src} alt={`DT Tour Philippines journey ${i+1}`}/></figure>)}</div></section>
  <section className="travelStoryLink"><p className="eyebrow">DT TOUR JOURNAL</p><h2>Read the full travel story.</h2><p>Discover how DT Tour connects private transport, local coordination, nature, heritage and island experiences in one flexible journey.</p><a className="primary darkPrimary" href="/news/dt-tour-philippines-curated-journeys">Read the article →</a></section>
  <section className="cta tourCta"><p className="eyebrow light">YOUR PHILIPPINES JOURNEY</p><h2>Tell us what you want to experience.</h2><p>We will help shape the route, transport and activities around your schedule.</p><a className="primary" target="_blank" rel="noreferrer" href="https://m.me/dulichphilippinesdttour">Message DT Tour</a></section>
</SubPage>}
